### ISSUE TITLE
[PE-D][Tester E] Confusing tags upon app initialisation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-3/tp#157]
![image.png](https://raw.githubusercontent.com/zacwong2151/ped/main/files/667527d4-a278-4403-9a80-7f52dbe494c1.png)

Upon app initialisation, tags show 'friends', 'colleagues' etc. when I expected to see genres or instruments. Only upon adding a musician then I realise that tag is not meant to be genre or instruments. Makes this confusing for users

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: zacwong2151/ped#1

**Comment by DeltonCheng** [comment]
Could add instrument tags / genre tags to the default addressbook to make it clearer

**Comment by tanyyyming** [comment]
This one is also considered feature flaw and we can't do anything about it sadly.
