### ISSUE TITLE
[PE-D][Tester B] "tag instrument" and "tag genre" are not valid commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-3/tp#165]
![image.png](https://raw.githubusercontent.com/cyaoxuan/ped/main/files/47dc7023-92ec-4b27-bb3c-eff0366c78d0.png)
Though "tag instrument" and "tag genre" were stated in the command summary of the UG, it is not a valid command in BandConnect++.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: cyaoxuan/ped#2

**Comment by DeltonCheng** [comment]
Update UG to the correct command
