### ISSUE TITLE
[PE-D][Tester E] Confusing command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-3/tp#173]
![image.png](https://raw.githubusercontent.com/zacwong2151/ped/main/files/4c4b4c33-49f0-4e5f-8899-338659c3b46c.png)

the purpose of this command is to `List the band members of a selected band`, and yet your command is `findb` and not `listb`. `findb` gives me the impression that you are trying to find that band, not list the musicians from that band

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: zacwong2151/ped#8

**Comment by DeltonCheng** [comment]
Clarify the statement in the UG, instead of using the word 'list', could change to "Find a band" and state that all musicians will be shown in the desciption?
