### ISSUE TITLE
[PE-D][Tester D] After using find the full initial person list is not being used.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-3/tp#174]
After using the find feature, the list feature must be used to access the full persons list. 
For example I wrote
`find n/Alexa`
this then outputted one person who's name is Alexa.
Afterwards if I were to enter
`edit 2 n/Apple`
I get an error message stating that `The musician index provided is invalid`

**Edit after filter**

![image.png](https://raw.githubusercontent.com/maj0-0/ped/main/files/07c66c7f-530a-4eba-b488-02f6b9f37359.png)

**List showing person 2 included**

![image.png](https://raw.githubusercontent.com/maj0-0/ped/main/files/c7afe56a-16bb-4f4b-ba83-288d1e34ef70.png)

It works after I type list though! Maybe you can approach this by making sure it is showing the full band list and person list at the beginning of each command! It should be similar to what's in list.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: maj0-0/ped#2

**Comment by DeltonCheng** [comment]
Not sure if this should be implemented. What if I would like to edit a musician on the filtered list. It is highly likely that I would filter the list before editing when I have large amounts of contacts.

Could give a warning / note under the relevant sections "If you would like to edit/delete etc a musician that is not shown, use list command first"

**Comment by tanyyyming** [comment]
Don't think it is considered a feature flaw. Probably not going to fix it.

**Comment by tanyyyming** [comment]
Anyone feel free to re-open this issue if you have better suggestions :)!
