### ISSUE TITLE
[PE-D][Tester C] Missing images for removem

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-3/tp#181]
![image.png](https://raw.githubusercontent.com/junnengsoo/ped/main/files/f484e427-4c73-441e-9fa9-9e0e0c7b4fd0.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: junnengsoo/ped#5

**Comment by DeltonCheng** [comment]
Related to #177
