### ISSUE TITLE
Fix bug: unexpected behaviour when adding multiple musicians into one band

### ISSUE THREAD

**Issue by tanyyyming** [AY2324S1-CS2103T-W11-3/tp#96]
When input `addm min/1 min/2 bin/0`, only the musician with index 2 (zero-based) is added to the band but not the musician with index 1.

**Comment by yytan25** [comment]
Thanks for bringing this up. Currently, the `AddMusicianToBand` command does not support adding multiple musicians into a band. We will decide how this behaviour is handled in a later iteration.

**Comment by tanyyyming** [comment]
Fixed by #137.
